import { AuthResponse } from "@rms/protocol";

import { type Db, SettingKey, getSetting } from "./db.ts";

/**
 * Proving a device is who it says it is.
 *
 * Challenge–response over Ed25519 rather than a bearer token: nothing
 * long-lived crosses the wire, a captured frame is useless once its nonce is
 * spent, and revoking a device is deleting one row.
 *
 *   server                                        device
 *     │── { nonce, serverTime } ────────────────▶ │
 *     │                                           │ sign(raw nonce bytes)
 *     │◀── { deviceId, signature, identity } ──── │
 *     │  look up the stored public key
 *     │  verify — the nonce is now spent
 *
 * The nonce is generated by the server, used once, and tied to the connection
 * it was issued on. A device does not get to pick what it signs; if it did, it
 * could replay one good signature forever.
 */

/** Long enough for a slow link, short enough that a captured nonce is stale. */
export const NONCE_TTL_MS = 30_000;
const NONCE_BYTES = 32;

/**
 * Decode base64 into a standalone `Uint8Array`.
 *
 * `Buffer.from` returns a view into Node's shared pool, which WebCrypto's types
 * reject (`ArrayBufferLike` vs `ArrayBuffer`). Copying through the `Uint8Array`
 * constructor gives a buffer of exactly the right length that nothing else
 * shares — cheap at these sizes, and it removes any question of neighbouring
 * pool bytes ever being in scope.
 */
export function decodeBase64(value: string): Uint8Array<ArrayBuffer> {
  return new Uint8Array(Buffer.from(value, "base64"));
}

export type AuthFailure =
  | "malformed"
  | "unknown_device"
  | "bad_signature"
  | "nonce_expired"
  | "nonce_spent";

export type AuthOutcome =
  | { ok: true; deviceId: string }
  | { ok: false; reason: AuthFailure };

export interface Challenge {
  nonce: string;
  serverTime: string;
  issuedAt: number;
}

export function issueChallenge(now: number): Challenge {
  const bytes = crypto.getRandomValues(new Uint8Array(NONCE_BYTES));
  return {
    nonce: Buffer.from(bytes).toString("base64"),
    serverTime: new Date(now).toISOString(),
    issuedAt: now,
  };
}

/**
 * Verify a device's answer to a challenge.
 *
 * `challenge` must be the one this connection issued, and the caller must
 * discard it afterwards regardless of the outcome — a nonce that survives a
 * failed attempt can be retried against.
 */
export async function verifyResponse(
  db: Db,
  challenge: Challenge,
  rawBody: unknown,
  now: number,
): Promise<AuthOutcome> {
  if (now - challenge.issuedAt > NONCE_TTL_MS) {
    return { ok: false, reason: "nonce_expired" };
  }

  const parsed = AuthResponse.safeParse(rawBody);
  if (!parsed.success) return { ok: false, reason: "malformed" };

  const { deviceId, signature, identity } = parsed.data;

  const device = db
    .query<{ public_key: string }, [string]>("SELECT public_key FROM devices WHERE id = ?")
    .get(deviceId);
  if (!device) return { ok: false, reason: "unknown_device" };

  const verified = await verifySignature(
    device.public_key,
    signature,
    // Sign over the raw nonce bytes, not their base64 text: the encoding is a
    // transport detail, and pinning the bytes means both sides cannot disagree
    // about padding or whitespace.
    decodeBase64(challenge.nonce),
  );
  if (!verified) return { ok: false, reason: "bad_signature" };

  // The identity block is refreshed on every connect so the dashboard survives
  // an OS upgrade or a rename without a re-enrollment. It is still untrusted
  // labelling — it cannot change which device this is, only what it's called.
  db.query<never, [string, string | null, number, string]>(
    "UPDATE devices SET identity = ?, machine_id = COALESCE(?, machine_id), last_seen_at = ? WHERE id = ?",
  ).run(JSON.stringify(identity), identity.machineId ?? null, now, deviceId);

  return { ok: true, deviceId };
}

async function verifySignature(
  publicKeyB64: string,
  signatureB64: string,
  message: Uint8Array<ArrayBuffer>,
): Promise<boolean> {
  try {
    const key = await crypto.subtle.importKey(
      "raw",
      decodeBase64(publicKeyB64),
      { name: "Ed25519" },
      false,
      ["verify"],
    );
    return await crypto.subtle.verify(
      { name: "Ed25519" },
      key,
      decodeBase64(signatureB64),
      message,
    );
  } catch {
    // A malformed key or signature is a failed verification, not a 500. The
    // stored key came from a schema-validated enrollment, so this is mostly a
    // guard against a hand-edited database.
    return false;
  }
}

/** Used by the WS handler to name itself to clients. */
export function serverName(db: Db): string {
  return getSetting(db, SettingKey.ServerName) ?? "control";
}
